# Generated by Django 3.2.7 on 2021-11-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
